import { Link } from 'react-router-dom';

export function TermsOfService() {
    return (
        <div style={{ maxWidth: '800px', margin: '0 auto' }}>
            <Link to="/" style={{ color: 'var(--text-dark)', textDecoration: 'none', marginBottom: '1.5rem', display: 'inline-block', fontFamily: 'var(--font-mono)', fontWeight: 'bold' }}>
                [← RETURN TO DATABASE ROOT]
            </Link>
            <div className="dossier-card">
                <h1 className="official-header" style={{ borderBottom: '3px solid black', paddingBottom: '0.5rem', marginBottom: '1.5rem' }}>
                    Terms of Service & Investigative Disclaimer
                </h1>
                
                <div style={{ fontFamily: 'var(--font-sans)', lineHeight: '1.6' }}>
                    <div className="dossier-status" style={{ display: 'inline-block', marginBottom: '1.5rem', transform: 'rotate(-2deg)' }}>
                        WARNING: AUTOMATED HEURISTICS
                    </div>
                    
                    <p style={{ marginBottom: '1.5rem', fontWeight: 'bold', color: 'var(--fbi-red)', fontSize: '1.1rem', borderLeft: '4px solid var(--fbi-red)', paddingLeft: '1rem' }}>
                        Disclaimer: The data presented in this database is generated by automated heuristics and may contain inaccuracies or false positives.
                    </p>
                    
                    <p style={{ marginBottom: '1.5rem' }}>
                        No user or player should be inherently discredited, harassed, or banned solely for registering a high Threat Score within this system. 
                        A high score indicates a statistical anomaly in behavioural patterns that requires further manual investigation by official Rugplay staff.
                    </p>
                    
                    <p style={{ marginBottom: '1.5rem' }}>
                        By using this database, you acknowledge that this is an <strong>unofficial, community-led investigative tool</strong> and its findings do not constitute absolute proof of malicious activity or explicit rules violations until verified by administrators.
                    </p>
                </div>
            </div>
        </div>
    );
}
