blank_issues_enabled: false
contact_links:
  - name: General Questions / Chat
    url: https://github.com/HoodClassic3000/The-Rugplay-FIles/discussions
    about: Got a random question or just want to talk data/metrics? Go to the discussions tab.
